#!/bin/sh
#

# PROVIDE: wg_slow
# REQUIRE: NETWORKING mountcritremote syslogd named

$_rc_subr_loaded . /etc/rc.subr

name="wg_slow"
command="/home/justin/bin/wg-slow"
rcvar=$name
start_cmd="wg_slow_start"
stop_cmd="wg_slow_stop"

: ${wg_slow_exe_path:=} 
: ${wg_interface:=wg0} 

wg_slow_start()
{
   ${command} ${wg_interface} false > /var/log/wg_slow.log 2>&1 &
}

wg_slow_stop()
{
    kill -9 $rc_pid
    ifconfig "${wg_interface}" destroy
}

load_rc_config $name
run_rc_command "$1"
